[package]
name = "ffi_plugin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
nostr-sdk = "0.21.0"

[build-dependencies]
cbindgen = "0.24.3"

[dev-dependencies]
